### ISSUE TITLE
How to use a new FIHR server?

### ISSUE THREAD

**Issue by sohrabhejazi** [lhncbc/lforms#11]
Hi,

I created an FHIR server and I want to connect to this server through your app and use my own data.
Is it possible? If yes, could you please guide me and tell me how?

LG
Sohrab

**Comment by plynchnlm** [comment]
If by "app" you mean our SMART on FHIR app, then go to https://lhncbc.github.io/lforms-fhir-app/.   You should be able to enter the URL for your FHIR server there.

However, this package on which you opened this issue is actually not for that app, but for the LForms widget which renders forms/questionnaires.  If you run into problems or have questions about the app, please open issues on the app's package, at https://github.com/lhncbc/lforms-fhir-app.
