### ISSUE TITLE
QuestionnaireResponse Resource not showing a LOINC Panel code

### ISSUE THREAD

**Issue by Matt2012** [lhncbc/lforms#68]
If a LHC form is saved as a FHIR questionnaire resource it has a LOINC code and text display to make it clear which LOINC questionnaire panel it is.

However if it is saved as a questionnaire response resource there is nothing linking it to a specific LOINC panel.

https://www.awesomescreenshot.com/video/4437947?key=d9c316018d67fbf26c60f83774dfd235

This maybe correct and the questionnaire response resource should be linked directly to a questionnaire resource on the server?

**Comment by plynchnlm** [comment]
You are right.  Normally a QuestionnaireResponse should contain a "questionnaire" element which is (usually) a URL to the Questionnaire on the FHIR server.   However, in that video (which was very helpful to see what you referring to), the app you are using is https://lhcforms.nlm.nih.gov/lhcforms, which not actually connected to a FHIR server.   LHC-Forms leaves it up to the app to set that, and since the app in this case doesn't have a FHIR server, it doesn't set it.
