### ISSUE TITLE
rendering-xhtml problem

### ISSUE THREAD

**Issue by mgraauw** [lhncbc/lforms#77]
I cannot get the xhtml rendering to work. Uploading this:
`{
    "resourceType": "Questionnaire",
    "id": "demo1-transactions-2",
    "name": "meting_bericht",
    "title": "Meting bericht",
    "status": "draft",
    "item": [
        {
          "linkId": "1.2",
          "text": "Yes or No:",
          "_text": {
            "extension": [
              {
                "url": "http://hl7.org/fhir/StructureDefinition/rendering-xhtml",
                "valueString": "<i>Please</i> answer <b><u>Yes</u></b> or <b><u>No</u></b>:"
              }
            ]
          },
          "type": "display"
        }
    ]
}`
into https://lhcforms.nlm.nih.gov/lhcforms does not render the xhtml, but the plain item.text. Nor can I get a local html (with 29.3.1) to display correctly. Is there some templateOption which needs to be set? (setting allowHTMLInInstructions: true won't do)
The snippet is straight from: https://build.fhir.org/ig/HL7/sdc/examples.html#rendering-xhtml 
Using the snippet with rendering-style and color green works fine (with my local html file and on the demo site), so the problem seems to be with rendering xhtml. The sdc support page (https://github.com/lhncbc/lforms/blob/master/sdc-support.md) seems to indicate xhtml is supported.

**Comment by plynchnlm** [comment]
LForms only has partial support for rendering-xhtml, which I see is not documented properly in r4-support.md.  In particular, we only support rendering-xhtml for help text (e.g., https://github.com/lhncbc/lforms/blob/master/test/data/R4/ussg-fhp.json).  It is in that context that allowHTMLInInstructions applies.  Also, we do not do any checking either for proper XHTML or for the limitations imposed on the XHTML by FHIR, but just allow any HTML there, which depending on your use case, might have security implications.  (See https://www.hl7.org/fhir/narrative.html#security .)  That being said, if you use it for help text items (as in ussg-fhp.json) and enable the showCodingInstruction to "inline", you can get the help text showing up on the page as if it were an item of type display, so that might be a work-around for your case.

**Comment by mgraauw** [comment]
Thx, clear. We control both the questionnaires and the forms, so the security is under our control too. The workaround might do, I see how it works.
