### ISSUE TITLE
AJAX autocompleter field with text from the another field in externallyDefined URL

### ISSUE THREAD

**Issue by Ajmal-M-A** [lhncbc/lforms#9]
I want fill the AJAX autocompleter field  based on a previous Item's input value. So i want to pass value from the previous input to the  externallyDefined URL. Is this possible? 

ie, Currently _term_ value is  the text from the field. I want a parameter like these that value will be  text from the another field.

**Comment by plynchnlm** [comment]
The expectation for the autocompleters is that they are providing matches based on what the user is typing in the current field.  So, there isn't support in the form definition for matching based on what the user typed in a different field, but there is support, via dataControl, to set a field's value based on another field.  So, you could set the second field to get the value of the first field when the user enters something there, and then when the AJAX search is triggered, it would use the value from its own field to trigger the search.

Alternatively, you could write a change event listener that updates the field's externallyDefined URL so that it includes the "terms" parameter.  I am not sure that would work well, because the field's externallyDefined URL will then append another "terms" parameter to the URL with the value of the field.  I am not sure what effect having two terms parameters would be on the receiving search system, and if the user has previously selected something from that field, then subsequent searches would likely not work.

If this search system is under your control, you might be able to configure it to accept the first field's value as a parameter with a different name.  The Clinical Table Search Service accepts an additional query string parameter "q", so if you had something like that the first field's value could go there and not conflict with the "terms" added by the AJAX field.

**Comment by Ajmal-M-A** [comment]
Hi @plynchnlm, Thanks for explanation. Search system is under our control and the server is ready to accept another variable. 

externallyDefined URL now only takes the predefined query parameters like authenticity_token,terms..etc  

How can I append additional query string parameter to externallyDefined URL dynamically?

**Comment by plynchnlm** [comment]
There is no real support for doing that, though there might be a way to hack in that behavior.  Please reconsider whether it would work to just let the user type the search string into the field that generates the autocompletion list, which follows the design.

If you really can't do it that way... then if you have the field ID for the AJAX autocompleter that you want to update, you can set its URL like:

$('#field_id_here')[0].autocomp.setURL(newURL);

I am not sure what side-effects this might result in, but a quick test I tried showed that to work.  One thing to watch out for is that if the item is repeating, and the user adds another, the new one (and maybe the old one) will be created with the old URL (without your "terms").  Also, if the form regenerates for some reason, the autocompleter might get reset.  If that is a problem, then you could also edit the form object's internal data, via the AngularJS scope, like $('#field_id_here').scope().$parent....$parent.item, where after some number of calls on $parent, you will find an item, will will give you access in the LFormsData structure, which you can traverse to find the right child item (item.items, or you might have to go the tree first) and the sent externallyDefined to your new URL.  That might be fragile with respect to updates of the LForms package.
