### ISSUE TITLE
Bad management of undefined

### ISSUE THREAD

**Issue by delcroip** [lhncbc/lforms#99]
First, thank you for the work you have done

I have some issue with fhirpath function, I guess it is mostly because the js doesn't catch properly the undefined.

in many place you have this is this
`value === undefined`
or this
`value !== undefined`
but I think, instead  it should be that 
`typeof value === 'undefined'`
and that 
`typeof value !== 'undefined'`

to test : https://lhcforms.nlm.nih.gov/lforms-fhir-app/?server=https%3A%2F%2Ffhir.dk.swisstph-mis.ch%2Fmatchbox%2Ffhir%2F

select EmCare.Registration.P, patient name 'Peter'

**Comment by plynchnlm** [comment]
I think ```value === undefined``` should be completely equivalent to ```typeof value === 'undefined'```, so I don't think the issue is there.

The first error I see when trying to load that form is that it is complaining about a uuid function not being defined.  When I look at the Questionnaire definition (http://[fhir.dk.swisstph-mis.ch/matchbox/fhir/Questionnaire/emcarea.registration.p](http://fhir.dk.swisstph-mis.ch/matchbox/fhir/Questionnaire/emcarea.registration.p), I see FHIRPath expressions "uuid()".  I don't see that function in the specification (either at http://hl7.org/fhirpath/N1/ or https://www.hl7.org/fhir/fhirpath.html), and we have not implemented such a function in fhirpath.js.

**Comment by delcroip** [comment]
I will closed that issue, it seems that the "Watch" on my browser dev mode doesn't work as I expected ( I think because of the minified code)

<img width="735" alt="image" src="https://user-images.githubusercontent.com/4052505/186347107-1ce2c574-a94a-425e-b6ac-474c0d74c22b.png">


value is actually called e 

I will open another one because I still have the e.toISOString error
